apiVersion: v1
kind: Pod
metadata:
  name: ${forms[0].data.name}
  namespace: ${forms[0].data.namespace}
spec:
  containers:
    - name: ${forms[0].data.name}-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: log_level
  restartPolicy: Never
